### PR TITLE
change to satisfies?

### PR DESCRIPTION
**Pull request by lalithr95**
Previous PR #23 was merged before `satisfies?` has been updated in the changes which is why master build is failing. This PR fixes build.

@jlindsey

### CODE REVIEW

**Comment by lalithr95** [comment]
bump ?

**Comment by jlindsey** [comment]
@lalithr95 Apologies, got busy and didn't have a chance to merge this.

**Comment by lalithr95** [comment]
Thanks! Np 👍

**Comment by perlun** [comment]
@lalithr95 _Please_, don't make these kind of changes in a publicly released version. Per the SemVer specification:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
>  1. MAJOR version when you make incompatible API changes,
>  2. MINOR version when you add functionality in a backwards-compatible manner, and
>  3. PATCH version when you make backwards-compatible bug fixes.
>
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

This change is definitely API incompatible. Our code used to work, but now after upgrading from 1.4.1 to 1.6.0 things broke for unknown reasons... until I started digging into the code and found this change. 😬 

I completely agree the change is good and valid, but this should rightfully have been put into a version 2.0 to clearly signify the semantics of this change. It _is_ a breaking change, and the major version number is exactly designed for this purpose.

We _do_ believe in Semantic Versioning here, don't we? 😂

**Comment by perlun** [comment]
For now, I suggest updating the 1.5.0 release notes here on GitHub indicating this (unintended) API breakage. We can all make mistakes like this, I don't intend to point fingers; I know how easy it is to slip like this. I just want to help make you and others aware of the problem.

**Comment by lalithr95** [comment]
@perlun sorry for the inconvenience caused. I'll note your points and make sure to release versions accordingly. My commit got merged, I totally forgot about the PR, I see now that version was released after my commit.  Looking carefully at the PR, this should backward compatible, #22 is the PR which missed right method name, but the next PR was merged soon after which should fix the issue. Also I believe no version was released in between bad and good commits.

**Comment by perlun** [comment]
@lalithr95 It's not backward compatible, because `satifies`/`satisfies?` is part of the public API. Our code looks like this:

```ruby
def version_specific_columns(base)
  target_version = Semantic::Version.new(config.fetch(:m3_version))
  return base unless target_version.satisfies('>= 13.2')
```

It broke because of the change introduced in #22. It was easily fixed but still, it broke and I had to dig up the code changes in the repo.

----

Only _private_ methods can be renamed like this, since they are not part of the public API. This is the practical application of the SemVer text:

> For this system to work, you first need to declare a public API. This may consist of documentation or be enforced by the code itself. Regardless, it is important that this API be clear and precise. Once you identify your public API, you communicate changes to it with specific increments to your version number. Consider a version format of X.Y.Z (Major.Minor.Patch). Bug fixes not affecting the API increment the patch version, backwards compatible API additions/changes increment the minor version, and backwards incompatible API changes increment the major version.
>
> ...
>
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
>
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
>
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.
>
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

**Pull request merged**
